### ISSUE TITLE
Clock works but "second" handle cannot go "up"

### ISSUE THREAD

**Issue by Silex** [akafugu/vetinari_clock#1]
Hello,

I successfully build the clock and it seems to work fine... except when I hang it on the wall. The "second" handle is not powerful enough to "climb" after the 45s mark. 

If I put one battery in the compartment of the mechanism then it has no problem doing so. If I put the clock horizontally then it also works.

My guess is that I didn't solder something properly and some voltage/current is lost somewhere... any idea of what I could do to fix it? I tried to measure the voltage/current but it looked ok...

**Comment by perjg** [comment]
We haven't seen this issue before. (Is this with the white Ikea clock or
with the smaller black clock?)
Checking your solder points and measuring the voltage from the batteries is
a good place to start.

It may be possible to adjust the firmware too, see the bottom of this page:
http://www.akafugu.jp/posts/products/vetinariclock/usage/

On Fri, Jan 24, 2014 at 11:17 PM, Philippe Vaucher <notifications@github.com

> wrote:
> 
> Hello,
> 
> I successfully build the clock and it seems to work fine... except when I
> hang it on the wall. The "second" handle is not powerful enough to "climb"
> after the 45s mark.
> 
> If I put one battery in the compartment of the mechanism then it has no
> problem doing so. If I put the clock horizontally then it also works.
> 
> My guess is that I didn't solder something properly and some
> voltage/current is lost somewhere... any idea of what I could do to fix it?
> I tried to measure the voltage/current but it looked ok...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/akafugu/vetinari_clock/issues/1
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by Silex** [comment]
Yes it's with teh white Ikea clock. I checked the voltages already at various points but it was always 3V like expected.

At the output I tried to measure the difference between the normal mechanism and the vetinari_clock mechanism but it's difficult because it seems like it "ticks" using a cycling voltage mechanism, e.g 8, 10, 12, 14, .. , 22 and back. The vetinari mechanism seems to produce the same kind of cycle, except values were a little lower (never went above 19)... At this point I stopped my investiguations and came to ask here :)

Can you tell me what voltage I should expect at the two green wires that goes into the normal clock mechanism?

Also, maybe it's not relevant but the mechanism inside the clock isn't excatly the same, I had to solder the green wires at a different place:

Received: http://unitedsoft.ch/vetinari.jpg
Original: http://www.akafugu.jp/images/products/vetinariclock/mechanism-new-11.jpg

**Comment by perjg** [comment]
It looks like there can be several different mechanism types inside the
clock. Your modification is still correct though, but it could be that your
mechanism works better with different values for ENERGISE_TIME. Do you have
an ISP programmer to test with?

On Wed, Jan 29, 2014 at 5:52 PM, Philippe Vaucher
notifications@github.comwrote:

> Yes it's with teh white Ikea clock. I checked the voltages already at
> various points but it was always 3V like expected.
> 
> At the output I tried to measure the difference between the normal
> mechanism and the vetinari_clock mechanism but it's difficult because it
> seems like it "ticks" using a cycling voltage mechanism, e.g 8, 10, 12, 14,
> .. , 22 and back. The vetinari mechanism seems to produce the same kind of
> cycle, except values were a little lower (never went above 19)... At this
> point I stopped my investiguations and came to ask here :)
> 
> Can you tell me what voltage I should expect at the two green wires that
> goes into the normal clock mechanism?
> 
> Also, maybe it's not relevant but the mechanism inside the clock isn't
> excatly the same, I had to solder the green wires at a different place:
> 
> Received: http://unitedsoft.ch/vetinari.jpg
> Original:
> http://www.akafugu.jp/images/products/vetinariclock/mechanism-new-11.jpg
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/akafugu/vetinari_clock/issues/1#issuecomment-33566209
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by Silex** [comment]
I have friends who do... I'll borrow one, what values should I try?

**Comment by perjg** [comment]
Up (and maybe down) in increments of 5 should do it.

On Wednesday, January 29, 2014, Philippe Vaucher notifications@github.com
wrote:

> I have friends who do... I'll borrow one, what values should I try?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/akafugu/vetinari_clock/issues/1#issuecomment-33568558
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by Silex** [comment]
Okay, using a `ENERGISE_TIME` value of 50 did the trick! I friend of mine suggested that maybe I put the capacitor in the wrong direction, do you think it's possible? My guess is that the mechanism wouldn't work at all if I did that.

Anyway, this friend of mine also bought one and it worked out of the box for him, so I guess I messed up somewhere when I soldered.

Thank you!

**Comment by perjg** [comment]
On Fri, Jan 31, 2014 at 9:02 PM, Philippe Vaucher
notifications@github.comwrote:

> Okay, using a ENERGISE_TIME value of 50 did the trick! I friend of mine
> suggested that maybe I put the capacitor in the wrong direction, do you
> think it's possible? My guess is that the mechanism wouldn't work at all if
> I did that.
> 
> If you put the electrolytic capacitor backwards, it probably wouldn't work
> at all (not sure if it would burn out from just being connected to the
> battery). You can double-check by comparing with this picture:
> http://www.akafugu.jp/images/products/vetinariclock/vetinariclock-10.jpg

The black stripe on the body of the cap should point in the same direction
as on the picture.

The picture you showed me earlier indicates that your mechanism is slightly
different from the one we use in the pictures, so that may have something
to do with it too. I'll try and make another one here and see if I can
replicate the issue.

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by Silex** [comment]
Well my cap is black but its white stripe points in the same direction as on the picture... But I remember messing up with the batteries at some point, maybe the cap is dead and doesn't charge anymore, and thus the pulse happen only with the batteries which would explain my very high ENERGISE_TIME value.

I'll try to replace the cap with a new one to see if that fixes it.

**Comment by Silex** [comment]
Okay well I couldn't test with another cap and it worked with a different ENERGISE_TIME value so now it's hanged in my office :)

You probably don't have to worry about this issue, I think it's just a side effect of my poor soldering skills... a friend of mine bought two of them and they work perfectly out of the box.
